configuration: Release
branches:
  only:
    - master

before_build:
  - nuget restore ..\wrappify.sln

build:
  project: wrappify.sln       
  verbosity: minimal

test:
  assemblies:
    - '**\*.Tests.dll'