configuration: Release
branches:
  only:
    - master

before_build:
  - nuget restore .\src\wrappify.sln

build:
  project: .\src\wrappify.sln      
  verbosity: minimal

test:
  assemblies:
    - '**\*.Tests.dll'