version: 1.0.{build}
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal